#!/usr/bin/env python3
# Copyright 2026 SEQSENSE, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Regenerate interface_aliases.txt, the list of core ROS 1 types to alias.

This is a maintenance tool, not part of the build. Only the *list* is
committed; the headers themselves are generated into the devel space at build
time by cmake/generate_ros1_compat_header.py --from-list.

Splitting it this way is what lets this package declare no dependency on any
of the interface packages below. Writing an alias needs neither the message
definition nor the defining package -- the #include it emits resolves in the
consumer's compilation. The packages are only needed to *enumerate* type
names, which is what this script does, once, out of band.

Run it against any environment with the core interfaces installed:

    python3 scripts/regen_interface_alias_list.py --ros-prefix /opt/ros/noetic
    python3 scripts/regen_interface_alias_list.py --check

ROS 1 is end-of-life, so these definitions are frozen; a re-run is only
needed when the package list below changes.
"""
import argparse
import os
import sys

# Core ROS 1 interface packages: std_msgs, std_srvs, the common_msgs stack
# and tf2_msgs. Extend deliberately -- every entry costs a line and nothing
# else, but an alias for a type ROS 2 does not have is a trap.
PACKAGES = [
    'actionlib_msgs',
    'diagnostic_msgs',
    'geometry_msgs',
    'nav_msgs',
    'sensor_msgs',
    'shape_msgs',
    'std_msgs',
    'std_srvs',
    'stereo_msgs',
    'tf2_msgs',
    'trajectory_msgs',
    'visualization_msgs',
]

_HERE = os.path.dirname(os.path.abspath(__file__))
_PKG_ROOT = os.path.dirname(_HERE)
_DEFAULT_LIST = os.path.join(_PKG_ROOT, 'interface_aliases.txt')

HEADER = """\
# Core ROS 1 interface types aliased into ROS 2 spelling, one per line as
#   <package>/<kind>/<TypeName>
#
# Generated by scripts/regen_interface_alias_list.py -- do not edit by hand.
# cmake/generate_ros1_compat_header.py --from-list expands this at build time.
#
# Actions are absent on purpose: ROS 1 expands Foo.action into seven flat
# messages, while ROS 2 models the same thing as one action type with nested
# Goal/Result/Feedback, so nav_msgs::msg::GetMapAction and friends would
# promise types ROS 2 never defines.
"""


def action_generated(share_dir):
    """
    Collect names genaction.py derives from *.action, which ROS 2 has no analogue for.

    ROS 1 expands Foo.action into seven flat messages; ROS 2 models the same
    thing as a single action type with nested Goal/Result/Feedback. Aliasing
    e.g. nav_msgs::msg::GetMapAction would promise a type ROS 2 never defines.
    """
    excluded = set()
    action_dir = os.path.join(share_dir, 'action')
    if not os.path.isdir(action_dir):
        return excluded
    for entry in sorted(os.listdir(action_dir)):
        if not entry.endswith('.action'):
            continue
        stem = entry[: -len('.action')]
        excluded.add(f'{stem}Action')
        for suffix in ('Goal', 'Result', 'Feedback'):
            excluded.add(f'{stem}Action{suffix}')
            excluded.add(f'{stem}{suffix}')
    return excluded


def collect(share_dir, kind):
    """Return type names for kind ('msg' or 'srv'), action spillover removed."""
    type_dir = os.path.join(share_dir, kind)
    if not os.path.isdir(type_dir):
        return []
    ext = '.' + kind
    excluded = action_generated(share_dir) if kind == 'msg' else set()
    names = [
        entry[: -len(ext)]
        for entry in os.listdir(type_dir)
        if entry.endswith(ext)
    ]
    return sorted(n for n in names if n not in excluded)


def build_list(ros_prefix):
    """Render the list file contents, or raise if a package is not installed."""
    missing = []
    lines = [HEADER]
    for package in PACKAGES:
        share_dir = os.path.join(ros_prefix, 'share', package)
        if not os.path.isdir(share_dir):
            missing.append(package)
            continue
        entries = [
            f'{package}/{kind}/{name}'
            for kind in ('msg', 'srv')
            for name in collect(share_dir, kind)
        ]
        if entries:
            lines.append('\n'.join(entries) + '\n')
    if missing:
        raise FileNotFoundError(
            f'not installed under {ros_prefix}: {" ".join(missing)}')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--ros-prefix',
        default=os.environ.get('ROS_PREFIX', '/opt/ros/noetic'),
        help='ROS 1 install prefix holding share/<package>/{msg,srv}',
    )
    parser.add_argument(
        '--list-file',
        default=_DEFAULT_LIST,
        help='List to write (default: this package\'s interface_aliases.txt)',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Do not write; exit non-zero if the committed list is stale',
    )
    args = parser.parse_args()

    try:
        content = build_list(args.ros_prefix)
    except FileNotFoundError as exc:
        print(f'error: {exc}', file=sys.stderr)
        return 1

    count = sum(1 for ln in content.splitlines() if ln and not ln.startswith('#'))

    if args.check:
        if not os.path.exists(args.list_file):
            print(f'error: {args.list_file} is missing', file=sys.stderr)
            return 1
        with open(args.list_file) as f:
            if f.read() != content:
                print(
                    f'error: {args.list_file} is out of date; '
                    f're-run without --check',
                    file=sys.stderr)
                return 1
        print(f'{args.list_file} is up to date ({count} entries)')
        return 0

    with open(args.list_file, 'w') as f:
        f.write(content)
    print(f'wrote {count} entries to {args.list_file}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
